spring:

  liquibase:
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: 123456789

server:
  port: 8080

yandex:
  cloud:
    api:
      key: key
      url: https://translate.api.cloud.yandex.net/translate/v2

translate:
  thread:
    count: 10